version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: HaircutFiveFriends
    restart: unless-stopped
    environment:
      POSTGRES_DB: HaircutFiveFriends
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: